-- Real customer import: CUSTOMERDATAFORCRM.xlsx (supplied by AKAI via Manus).
-- 206 rows: 102 under "SALE AGENT: HARRIS" (display name Haris) and 104 under "SALE AGENT: DANIYAL".
-- Rules from PROJECT_RULES.md:
--   * every row is an ordinary ACTIVE customer; no internal accounts; data_complete = false
--   * customer_type = OTHER; a keyword guess goes only into customer_type_suggestion
--   * Title Case business_name, UPPERCASE normalized_name
--   * import_key = workbook hash + source row, so the import is idempotent
--   * exact/near duplicates (>= 90% name similarity) are flagged for manual review, never merged
--   * area codes use the workbook abbreviation as name/town until an Admin fills them in
-- Sales Agent logins do not exist yet. Each customer keeps import_agent_alias (HARIS / DANIYAL);
-- when a Sales Agent with that agent code is created, a trigger assigns their customers.

alter table public.customers add column if not exists import_agent_alias text;
create index if not exists customers_import_agent_alias_idx on public.customers (import_agent_alias) where assigned_agent_id is null;

create or replace function public.canonical_agent_alias(p_value text)
returns text language sql immutable set search_path = public as $$
  select case when upper(trim(p_value)) in ('HARRIS', 'HARIS') then 'HARIS' else nullif(upper(trim(p_value)), '') end;
$$;

create or replace function public.assign_imported_customers_to_agent()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.customers c
     set assigned_agent_id = new.id, updated_at = now()
   where c.assigned_agent_id is null
     and c.import_agent_alias is not null
     and c.import_agent_alias = public.canonical_agent_alias(new.agent_code);
  return new;
end;
$$;
revoke all on function public.assign_imported_customers_to_agent() from public, anon, authenticated;
drop trigger if exists sales_agents_assign_imported_customers on public.sales_agents;
create trigger sales_agents_assign_imported_customers
  after insert or update of agent_code on public.sales_agents
  for each row execute function public.assign_imported_customers_to_agent();


insert into public.area_codes (code, full_name_en, full_name_ur, town) values
  ('---', '---', '---', '---'),
  ('----', '----', '----', '----'),
  ('4K', '4K', '4K', '4K'),
  ('AFSHANABAD', 'AFSHANABAD', 'AFSHANABAD', 'AFSHANABAD'),
  ('AFSHANI RD', 'AFSHANI RD', 'AFSHANI RD', 'AFSHANI RD'),
  ('AIRPORT', 'AIRPORT', 'AIRPORT', 'AIRPORT'),
  ('AKBAR RD', 'AKBAR RD', 'AKBAR RD', 'AKBAR RD'),
  ('ANDAMOR', 'ANDAMOR', 'ANDAMOR', 'ANDAMOR'),
  ('AYS', 'AYS', 'AYS', 'AYS'),
  ('AYS MANZIL', 'AYS MANZIL', 'AYS MANZIL', 'AYS MANZIL'),
  ('AYS MNZL', 'AYS MNZL', 'AYS MNZL', 'AYS MNZL'),
  ('B.Z', 'B.Z', 'B.Z', 'B.Z'),
  ('BANARAS', 'BANARAS', 'BANARAS', 'BANARAS'),
  ('BOLTON', 'BOLTON', 'BOLTON', 'BOLTON'),
  ('BORAPIR', 'BORAPIR', 'BORAPIR', 'BORAPIR'),
  ('BUFFER ZONE', 'BUFFER ZONE', 'BUFFER ZONE', 'BUFFER ZONE'),
  ('CLIFTON', 'CLIFTON', 'CLIFTON', 'CLIFTON'),
  ('CREEK VISTA', 'CREEK VISTA', 'CREEK VISTA', 'CREEK VISTA'),
  ('DHA', 'DHA', 'DHA', 'DHA'),
  ('DHA 1', 'DHA 1', 'DHA 1', 'DHA 1'),
  ('DHA 2', 'DHA 2', 'DHA 2', 'DHA 2'),
  ('DHA 4', 'DHA 4', 'DHA 4', 'DHA 4'),
  ('DHA 5', 'DHA 5', 'DHA 5', 'DHA 5'),
  ('DHA 7', 'DHA 7', 'DHA 7', 'DHA 7'),
  ('GIZRI', 'GIZRI', 'GIZRI', 'GIZRI'),
  ('GOLIMAR', 'GOLIMAR', 'GOLIMAR', 'GOLIMAR'),
  ('GUL', 'GUL', 'GUL', 'GUL'),
  ('GUL 13-B', 'GUL 13-B', 'GUL 13-B', 'GUL 13-B'),
  ('GUL 13D/2', 'GUL 13D/2', 'GUL 13D/2', 'GUL 13D/2'),
  ('GUL B13', 'GUL B13', 'GUL B13', 'GUL B13'),
  ('GUL B7', 'GUL B7', 'GUL B7', 'GUL B7'),
  ('GULSHAN', 'GULSHAN', 'GULSHAN', 'GULSHAN'),
  ('GULSHAN 13', 'GULSHAN 13', 'GULSHAN 13', 'GULSHAN 13'),
  ('GULSHAN B5', 'GULSHAN B5', 'GULSHAN B5', 'GULSHAN B5'),
  ('HYDRI', 'HYDRI', 'HYDRI', 'HYDRI'),
  ('IMRAN/KDA', 'IMRAN/KDA', 'IMRAN/KDA', 'IMRAN/KDA'),
  ('JAMSHED RD', 'JAMSHED RD', 'JAMSHED RD', 'JAMSHED RD'),
  ('JHR', 'JHR', 'JHR', 'JHR'),
  ('JHR PERFUME CWK', 'JHR PERFUME CWK', 'JHR PERFUME CWK', 'JHR PERFUME CWK'),
  ('JODIA BZR', 'JODIA BZR', 'JODIA BZR', 'JODIA BZR'),
  ('KDA', 'KDA', 'KDA', 'KDA'),
  ('KHRDR', 'KHRDR', 'KHRDR', 'KHRDR'),
  ('KORNAGI', 'KORNAGI', 'KORNAGI', 'KORNAGI'),
  ('LQT', 'LQT', 'LQT', 'LQT'),
  ('LQTB', 'LQTB', 'LQTB', 'LQTB'),
  ('MALIR', 'MALIR', 'MALIR', 'MALIR'),
  ('MANZOOR CLNY', 'MANZOOR CLNY', 'MANZOOR CLNY', 'MANZOOR CLNY'),
  ('MARIPUR', 'MARIPUR', 'MARIPUR', 'MARIPUR'),
  ('MAYMAR', 'MAYMAR', 'MAYMAR', 'MAYMAR'),
  ('MDL CLNY', 'MDL CLNY', 'MDL CLNY', 'MDL CLNY'),
  ('MODEL COLONY', 'MODEL COLONY', 'MODEL COLONY', 'MODEL COLONY'),
  ('MOSMIYAT', 'MOSMIYAT', 'MOSMIYAT', 'MOSMIYAT'),
  ('N. KH', 'N. KH', 'N. KH', 'N. KH'),
  ('N.KHI', 'N.KHI', 'N.KHI', 'N.KHI'),
  ('N.N', 'N.N', 'N.N', 'N.N'),
  ('N.N 3', 'N.N 3', 'N.N 3', 'N.N 3'),
  ('N.N HYDRI', 'N.N HYDRI', 'N.N HYDRI', 'N.N HYDRI'),
  ('N.N3', 'N.N3', 'N.N3', 'N.N3'),
  ('N1', 'N1', 'N1', 'N1'),
  ('NAGIN', 'NAGIN', 'NAGIN', 'NAGIN'),
  ('NURSERY', 'NURSERY', 'NURSERY', 'NURSERY'),
  ('NZM N3', 'NZM N3', 'NZM N3', 'NZM N3'),
  ('NZMB N3', 'NZMB N3', 'NZMB N3', 'NZMB N3'),
  ('OLD', 'OLD', 'OLD', 'OLD'),
  ('OLD SABZI MANDI', 'OLD SABZI MANDI', 'OLD SABZI MANDI', 'OLD SABZI MANDI'),
  ('PAKISTAN CHK', 'PAKISTAN CHK', 'PAKISTAN CHK', 'PAKISTAN CHK'),
  ('PHASE 4', 'PHASE 4', 'PHASE 4', 'PHASE 4'),
  ('PHASE 8', 'PHASE 8', 'PHASE 8', 'PHASE 8'),
  ('PIYALA HOTEL', 'PIYALA HOTEL', 'PIYALA HOTEL', 'PIYALA HOTEL'),
  ('PLAZA', 'PLAZA', 'PLAZA', 'PLAZA'),
  ('QAYUMABAD', 'QAYUMABAD', 'QAYUMABAD', 'QAYUMABAD'),
  ('RIZVIA', 'RIZVIA', 'RIZVIA', 'RIZVIA'),
  ('SADDAR', 'SADDAR', 'SADDAR', 'SADDAR'),
  ('SAFOORA', 'SAFOORA', 'SAFOORA', 'SAFOORA'),
  ('SAFORA', 'SAFORA', 'SAFORA', 'SAFORA'),
  ('SAFORA GOTH', 'SAFORA GOTH', 'SAFORA GOTH', 'SAFORA GOTH'),
  ('SAGEER CENTER', 'SAGEER CENTER', 'SAGEER CENTER', 'SAGEER CENTER'),
  ('SAGEER CNTR', 'SAGEER CNTR', 'SAGEER CNTR', 'SAGEER CNTR'),
  ('SALEEM CENTER', 'SALEEM CENTER', 'SALEEM CENTER', 'SALEEM CENTER'),
  ('SHDMN T', 'SHDMN T', 'SHDMN T', 'SHDMN T'),
  ('SHE FAISAL', 'SHE FAISAL', 'SHE FAISAL', 'SHE FAISAL'),
  ('SHE-FAISLA', 'SHE-FAISLA', 'SHE-FAISLA', 'SHE-FAISLA'),
  ('SLDR BZR', 'SLDR BZR', 'SLDR BZR', 'SLDR BZR'),
  ('SOLDIER BZR', 'SOLDIER BZR', 'SOLDIER BZR', 'SOLDIER BZR'),
  ('TARIQ RD', 'TARIQ RD', 'TARIQ RD', 'TARIQ RD'),
  ('UP', 'UP', 'UP', 'UP'),
  ('W.P', 'W.P', 'W.P', 'W.P'),
  ('ZAMZAMA', 'ZAMZAMA', 'ZAMZAMA', 'ZAMZAMA')
on conflict (code) do nothing;

insert into public.customers (name, business_name, normalized_name, area_code, status, is_active, is_internal_account, data_complete, customer_type, customer_type_suggestion, duplicate_review_required, duplicate_review_reason, import_batch_id, import_source_row, import_key, imported_at, import_agent_alias) values
  ('A.B Shah Autos', 'A.B Shah Autos', 'AB SHAH AUTOS', 'AFSHANI RD', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 3, '07aba47e9677:3', now(), 'HARIS'),
  ('AB & Sons', 'AB & Sons', 'AB & SONS', 'SLDR BZR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 4, '07aba47e9677:4', now(), 'HARIS'),
  ('Abbasi Paint House', 'Abbasi Paint House', 'ABBASI PAINT HOUSE', 'HYDRI', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 5, '07aba47e9677:5', now(), 'HARIS'),
  ('Afsar Hardware', 'Afsar Hardware', 'AFSAR HARDWARE', 'LQTB', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 6, '07aba47e9677:6', now(), 'HARIS'),
  ('Al Habib Petroleum', 'Al Habib Petroleum', 'AL HABIB PETROLEUM', 'N1', 'ACTIVE', true, false, false, 'OTHER', 'FUEL_STATION'::"CustomerType", false, null, '07aba47e9677', 7, '07aba47e9677:7', now(), 'HARIS'),
  ('Al Makkah Autos', 'Al Makkah Autos', 'AL MAKKAH AUTOS', 'SALEEM CENTER', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: AL-MAKKAH AUTO (row 13)', '07aba47e9677', 8, '07aba47e9677:8', now(), 'HARIS'),
  ('Al Momin Auto', 'Al Momin Auto', 'AL MOMIN AUTO', 'AYS MANZIL', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 9, '07aba47e9677:9', now(), 'HARIS'),
  ('Al Saddat Oil Change 2', 'Al Saddat Oil Change 2', 'AL SADDAT OIL CHANGE 2', 'SAFORA', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 10, '07aba47e9677:10', now(), 'HARIS'),
  ('Al Safa Super Market', 'Al Safa Super Market', 'AL SAFA SUPER MARKET', 'JHR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 11, '07aba47e9677:11', now(), 'HARIS'),
  ('Al Tawaqal Auto', 'Al Tawaqal Auto', 'AL TAWAQAL AUTO', 'AYS MANZIL', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 12, '07aba47e9677:12', now(), 'HARIS'),
  ('Al-Makkah Auto', 'Al-Makkah Auto', 'ALMAKKAH AUTO', 'GULSHAN B5', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: AL MAKKAH AUTOS (row 8)', '07aba47e9677', 13, '07aba47e9677:13', now(), 'HARIS'),
  ('Al-Makkah Lubricant', 'Al-Makkah Lubricant', 'ALMAKKAH LUBRICANT', 'MAYMAR', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 14, '07aba47e9677:14', now(), 'HARIS'),
  ('Al-Sami Hardware', 'Al-Sami Hardware', 'ALSAMI HARDWARE', 'GULSHAN 13', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 15, '07aba47e9677:15', now(), 'HARIS'),
  ('Ali Autos', 'Ali Autos', 'ALI AUTOS', 'ANDAMOR', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 16, '07aba47e9677:16', now(), 'HARIS'),
  ('Ali Shah Autos', 'Ali Shah Autos', 'ALI SHAH AUTOS', 'N.N', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 17, '07aba47e9677:17', now(), 'HARIS'),
  ('Aly Autos', 'Aly Autos', 'ALY AUTOS', 'N.N 3', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 18, '07aba47e9677:18', now(), 'HARIS'),
  ('Asif Bhai Polish', 'Asif Bhai Polish', 'ASIF BHAI POLISH', 'BORAPIR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 19, '07aba47e9677:19', now(), 'HARIS'),
  ('Attari Autos', 'Attari Autos', 'ATTARI AUTOS', 'AYS MNZL', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 20, '07aba47e9677:20', now(), 'HARIS'),
  ('Auto Oil Trader', 'Auto Oil Trader', 'AUTO OIL TRADER', 'HYDRI', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 21, '07aba47e9677:21', now(), 'HARIS'),
  ('Baba Autos', 'Baba Autos', 'BABA AUTOS', 'GUL B7', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 22, '07aba47e9677:22', now(), 'HARIS'),
  ('Bilal Autos', 'Bilal Autos', 'BILAL AUTOS', 'AYS MNZL', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: BILAL AUTOS (row 24)', '07aba47e9677', 23, '07aba47e9677:23', now(), 'HARIS'),
  ('Bilal Autos', 'Bilal Autos', 'BILAL AUTOS', 'NZMB N3', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: BILAL AUTOS (row 23)', '07aba47e9677', 24, '07aba47e9677:24', now(), 'HARIS'),
  ('Bin Zafi Lube Mart', 'Bin Zafi Lube Mart', 'BIN ZAFI LUBE MART', 'AFSHANABAD', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 25, '07aba47e9677:25', now(), 'HARIS'),
  ('Burhani Enterprises', 'Burhani Enterprises', 'BURHANI ENTERPRISES', 'JODIA BZR', 'ACTIVE', true, false, false, 'OTHER', 'DISTRIBUTOR'::"CustomerType", false, null, '07aba47e9677', 26, '07aba47e9677:26', now(), 'HARIS'),
  ('Car Care Saad', 'Car Care Saad', 'CAR CARE SAAD', 'HYDRI', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 27, '07aba47e9677:27', now(), 'HARIS'),
  ('Car Care Saif', 'Car Care Saif', 'CAR CARE SAIF', 'HYDRI', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 28, '07aba47e9677:28', now(), 'HARIS'),
  ('Car Madico', 'Car Madico', 'CAR MADICO', 'SAFORA', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 29, '07aba47e9677:29', now(), 'HARIS'),
  ('Car Zone', 'Car Zone', 'CAR ZONE', 'NAGIN', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 30, '07aba47e9677:30', now(), 'HARIS'),
  ('Chaman Auto', 'Chaman Auto', 'CHAMAN AUTO', 'AYS MNZL', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 31, '07aba47e9677:31', now(), 'HARIS'),
  ('Decent Paint', 'Decent Paint', 'DECENT PAINT', 'HYDRI', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 32, '07aba47e9677:32', now(), 'HARIS'),
  ('DK Motors', 'DK Motors', 'DK MOTORS', 'SAGEER CENTER', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 33, '07aba47e9677:33', now(), 'HARIS'),
  ('Easy Multicolor', 'Easy Multicolor', 'EASY MULTICOLOR', 'UP', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 34, '07aba47e9677:34', now(), 'HARIS'),
  ('Ebd-Rehman Paint House', 'Ebd-Rehman Paint House', 'EBDREHMAN PAINT HOUSE', 'W.P', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 35, '07aba47e9677:35', now(), 'HARIS'),
  ('Ejaz Hardware', 'Ejaz Hardware', 'EJAZ HARDWARE', 'LQTB', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 36, '07aba47e9677:36', now(), 'HARIS'),
  ('Exclusive Auto Amir', 'Exclusive Auto Amir', 'EXCLUSIVE AUTO AMIR', 'KDA', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 37, '07aba47e9677:37', now(), 'HARIS'),
  ('Fahad Lubricant', 'Fahad Lubricant', 'FAHAD LUBRICANT', 'B.Z', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 38, '07aba47e9677:38', now(), 'HARIS'),
  ('Faisal Autos', 'Faisal Autos', 'FAISAL AUTOS', 'JAMSHED RD', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 39, '07aba47e9677:39', now(), 'HARIS'),
  ('Faizan Autos', 'Faizan Autos', 'FAIZAN AUTOS', 'AKBAR RD', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 40, '07aba47e9677:40', now(), 'HARIS'),
  ('Gayaz Car', 'Gayaz Car', 'GAYAZ CAR', 'PIYALA HOTEL', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 41, '07aba47e9677:41', now(), 'HARIS'),
  ('Ghazi Autos', 'Ghazi Autos', 'GHAZI AUTOS', 'SAGEER CNTR', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: GHAZI AUTOS (row 151)', '07aba47e9677', 42, '07aba47e9677:42', now(), 'HARIS'),
  ('Ghosia Hardware Store', 'Ghosia Hardware Store', 'GHOSIA HARDWARE STORE', 'GUL 13D/2', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 43, '07aba47e9677:43', now(), 'HARIS'),
  ('Gold Star', 'Gold Star', 'GOLD STAR', 'SAFORA', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 44, '07aba47e9677:44', now(), 'HARIS'),
  ('Good Luck Auto', 'Good Luck Auto', 'GOOD LUCK AUTO', 'N.KHI', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 45, '07aba47e9677:45', now(), 'HARIS'),
  ('Gulf Autos', 'Gulf Autos', 'GULF AUTOS', 'AYS MANZIL', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 46, '07aba47e9677:46', now(), 'HARIS'),
  ('Gulzar Petroleum', 'Gulzar Petroleum', 'GULZAR PETROLEUM', 'BUFFER ZONE', 'ACTIVE', true, false, false, 'OTHER', 'FUEL_STATION'::"CustomerType", false, null, '07aba47e9677', 47, '07aba47e9677:47', now(), 'HARIS'),
  ('H.M Autos', 'H.M Autos', 'HM AUTOS', 'W.P', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 48, '07aba47e9677:48', now(), 'HARIS'),
  ('Haidra Autos', 'Haidra Autos', 'HAIDRA AUTOS', 'SAFORA GOTH', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 49, '07aba47e9677:49', now(), 'HARIS'),
  ('Hanif Sampling Account', 'Hanif Sampling Account', 'HANIF SAMPLING ACCOUNT', '----', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 50, '07aba47e9677:50', now(), 'HARIS'),
  ('Hanif Supply Cash Sale', 'Hanif Supply Cash Sale', 'HANIF SUPPLY CASH SALE', '----', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 51, '07aba47e9677:51', now(), 'HARIS'),
  ('Hassan Hardware', 'Hassan Hardware', 'HASSAN HARDWARE', 'GOLIMAR', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 52, '07aba47e9677:52', now(), 'HARIS'),
  ('Hazari Enterprises', 'Hazari Enterprises', 'HAZARI ENTERPRISES', 'OLD', 'ACTIVE', true, false, false, 'OTHER', 'DISTRIBUTOR'::"CustomerType", false, null, '07aba47e9677', 53, '07aba47e9677:53', now(), 'HARIS'),
  ('HGM Oil Change', 'HGM Oil Change', 'HGM OIL CHANGE', 'OLD SABZI MANDI', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 54, '07aba47e9677:54', now(), 'HARIS'),
  ('HS Lubricants Autos', 'HS Lubricants Autos', 'HS LUBRICANTS AUTOS', 'SHDMN T', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 55, '07aba47e9677:55', now(), 'HARIS'),
  ('Imran Autos', 'Imran Autos', 'IMRAN AUTOS', 'RIZVIA', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 56, '07aba47e9677:56', now(), 'HARIS'),
  ('Imran Paint', 'Imran Paint', 'IMRAN PAINT', 'JHR PERFUME CWK', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 57, '07aba47e9677:57', now(), 'HARIS'),
  ('Insaf Car Wash & Oil', 'Insaf Car Wash & Oil', 'INSAF CAR WASH & OIL', 'MAYMAR', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 58, '07aba47e9677:58', now(), 'HARIS'),
  ('K.B Traders', 'K.B Traders', 'KB TRADERS', 'PAKISTAN CHK', 'ACTIVE', true, false, false, 'OTHER', 'DISTRIBUTOR'::"CustomerType", false, null, '07aba47e9677', 59, '07aba47e9677:59', now(), 'HARIS'),
  ('Kashif Autos', 'Kashif Autos', 'KASHIF AUTOS', 'AFSHANI RD', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 60, '07aba47e9677:60', now(), 'HARIS'),
  ('Khaliq Autos', 'Khaliq Autos', 'KHALIQ AUTOS', 'N.N', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 61, '07aba47e9677:61', now(), 'HARIS'),
  ('Khan Auto Impex', 'Khan Auto Impex', 'KHAN AUTO IMPEX', 'N. KH', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 62, '07aba47e9677:62', now(), 'HARIS'),
  ('Khyber Pain T', 'Khyber Pain T', 'KHYBER PAIN T', 'GUL B13', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 63, '07aba47e9677:63', now(), 'HARIS'),
  ('Lasani Paint House', 'Lasani Paint House', 'LASANI PAINT HOUSE', 'NZM N3', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 64, '07aba47e9677:64', now(), 'HARIS'),
  ('M.A Autos', 'M.A Autos', 'MA AUTOS', 'SAFORA', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: MNA AUTOS (row 74)', '07aba47e9677', 65, '07aba47e9677:65', now(), 'HARIS'),
  ('M.D & Sons', 'M.D & Sons', 'MD & SONS', 'LQTB', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 66, '07aba47e9677:66', now(), 'HARIS'),
  ('M.Y Autos', 'M.Y Autos', 'MY AUTOS', 'MAYMAR', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 67, '07aba47e9677:67', now(), 'HARIS'),
  ('M.Yahya Ags', 'M.Yahya Ags', 'MYAHYA AGS', 'PLAZA', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 68, '07aba47e9677:68', now(), 'HARIS'),
  ('Madina Paint & Hardware', 'Madina Paint & Hardware', 'MADINA PAINT & HARDWARE', 'W.P', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 69, '07aba47e9677:69', now(), 'HARIS'),
  ('Master Shine Detailing', 'Master Shine Detailing', 'MASTER SHINE DETAILING', 'N.N', 'ACTIVE', true, false, false, 'OTHER', 'DETAILING'::"CustomerType", false, null, '07aba47e9677', 70, '07aba47e9677:70', now(), 'HARIS'),
  ('Matee Khan', 'Matee Khan', 'MATEE KHAN', 'BANARAS', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 71, '07aba47e9677:71', now(), 'HARIS'),
  ('Mehfooz Autos', 'Mehfooz Autos', 'MEHFOOZ AUTOS', '4K', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 72, '07aba47e9677:72', now(), 'HARIS'),
  ('Mirza Autos', 'Mirza Autos', 'MIRZA AUTOS', 'LQTB', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 73, '07aba47e9677:73', now(), 'HARIS'),
  ('Mna Autos', 'Mna Autos', 'MNA AUTOS', 'JHR', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: M.A AUTOS (row 65)', '07aba47e9677', 74, '07aba47e9677:74', now(), 'HARIS'),
  ('Nadeem Auto', 'Nadeem Auto', 'NADEEM AUTO', 'N.N HYDRI', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 75, '07aba47e9677:75', now(), 'HARIS'),
  ('Nafay Autos', 'Nafay Autos', 'NAFAY AUTOS', 'GUL', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 76, '07aba47e9677:76', now(), 'HARIS'),
  ('Nehroz Khan', 'Nehroz Khan', 'NEHROZ KHAN', 'BANARAS', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 77, '07aba47e9677:77', now(), 'HARIS'),
  ('Nemat Khan', 'Nemat Khan', 'NEMAT KHAN', 'BANARAS', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 78, '07aba47e9677:78', now(), 'HARIS'),
  ('New Ammar Hardware', 'New Ammar Hardware', 'NEW AMMAR HARDWARE', 'HYDRI', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 79, '07aba47e9677:79', now(), 'HARIS'),
  ('New Gulf Autos', 'New Gulf Autos', 'NEW GULF AUTOS', 'IMRAN/KDA', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: NEW GULF AUTOS (row 81)', '07aba47e9677', 80, '07aba47e9677:80', now(), 'HARIS'),
  ('New Gulf Autos', 'New Gulf Autos', 'NEW GULF AUTOS', 'N.N3', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: NEW GULF AUTOS (row 80)', '07aba47e9677', 81, '07aba47e9677:81', now(), 'HARIS'),
  ('New Hardware House', 'New Hardware House', 'NEW HARDWARE HOUSE', 'UP', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 82, '07aba47e9677:82', now(), 'HARIS'),
  ('New Pak Hardware', 'New Pak Hardware', 'NEW PAK HARDWARE', 'GUL 13-B', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 83, '07aba47e9677:83', now(), 'HARIS'),
  ('New Vip Autos', 'New Vip Autos', 'NEW VIP AUTOS', 'AYS', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 84, '07aba47e9677:84', now(), 'HARIS'),
  ('Nexron Oil Trader', 'Nexron Oil Trader', 'NEXRON OIL TRADER', '4K', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 85, '07aba47e9677:85', now(), 'HARIS'),
  ('Pro Car Wash', 'Pro Car Wash', 'PRO CAR WASH', 'SAFOORA', 'ACTIVE', true, false, false, 'OTHER', 'CAR_WASH'::"CustomerType", false, null, '07aba47e9677', 86, '07aba47e9677:86', now(), 'HARIS'),
  ('Qutbi Supply', 'Qutbi Supply', 'QUTBI SUPPLY', 'BOLTON', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 87, '07aba47e9677:87', now(), 'HARIS'),
  ('R.R Auto Parts', 'R.R Auto Parts', 'RR AUTO PARTS', 'N.N', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 88, '07aba47e9677:88', now(), 'HARIS'),
  ('Raza Autos', 'Raza Autos', 'RAZA AUTOS', 'HYDRI', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 89, '07aba47e9677:89', now(), 'HARIS'),
  ('RB Enterprises', 'RB Enterprises', 'RB ENTERPRISES', 'SOLDIER BZR', 'ACTIVE', true, false, false, 'OTHER', 'DISTRIBUTOR'::"CustomerType", false, null, '07aba47e9677', 90, '07aba47e9677:90', now(), 'HARIS'),
  ('Shams Paint House', 'Shams Paint House', 'SHAMS PAINT HOUSE', 'LQT', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 91, '07aba47e9677:91', now(), 'HARIS'),
  ('Siddiqi Autos', 'Siddiqi Autos', 'SIDDIQI AUTOS', 'ANDAMOR', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 92, '07aba47e9677:92', now(), 'HARIS'),
  ('Sikander Car Wash', 'Sikander Car Wash', 'SIKANDER CAR WASH', 'MOSMIYAT', 'ACTIVE', true, false, false, 'OTHER', 'CAR_WASH'::"CustomerType", false, null, '07aba47e9677', 93, '07aba47e9677:93', now(), 'HARIS'),
  ('Solar Gard', 'Solar Gard', 'SOLAR GARD', 'AYS MNZL', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 94, '07aba47e9677:94', now(), 'HARIS'),
  ('Subhan Enterprises', 'Subhan Enterprises', 'SUBHAN ENTERPRISES', 'N.N3', 'ACTIVE', true, false, false, 'OTHER', 'DISTRIBUTOR'::"CustomerType", false, null, '07aba47e9677', 95, '07aba47e9677:95', now(), 'HARIS'),
  ('Super Autos', 'Super Autos', 'SUPER AUTOS', 'AYS MANZIL', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 96, '07aba47e9677:96', now(), 'HARIS'),
  ('Supreme Paint Store', 'Supreme Paint Store', 'SUPREME PAINT STORE', 'HYDRI', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 97, '07aba47e9677:97', now(), 'HARIS'),
  ('Taha Autos', 'Taha Autos', 'TAHA AUTOS', 'HYDRI', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 98, '07aba47e9677:98', now(), 'HARIS'),
  ('Talron Lube', 'Talron Lube', 'TALRON LUBE', 'GULSHAN', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 99, '07aba47e9677:99', now(), 'HARIS'),
  ('Tawaqal Autos', 'Tawaqal Autos', 'TAWAQAL AUTOS', 'KDA', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 100, '07aba47e9677:100', now(), 'HARIS'),
  ('Yasir Auto', 'Yasir Auto', 'YASIR AUTO', 'GULSHAN B5', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: YASIR AUTOS (row 102)', '07aba47e9677', 101, '07aba47e9677:101', now(), 'HARIS'),
  ('Yasir Autos', 'Yasir Autos', 'YASIR AUTOS', 'KDA', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: YASIR AUTO (row 101)', '07aba47e9677', 102, '07aba47e9677:102', now(), 'HARIS'),
  ('Z.S Traders', 'Z.S Traders', 'ZS TRADERS', 'N.N', 'ACTIVE', true, false, false, 'OTHER', 'DISTRIBUTOR'::"CustomerType", false, null, '07aba47e9677', 103, '07aba47e9677:103', now(), 'HARIS'),
  ('Zahid Autos', 'Zahid Autos', 'ZAHID AUTOS', 'ANDAMOR', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 104, '07aba47e9677:104', now(), 'HARIS'),
  ('A1 Store', 'A1 Store', 'A1 STORE', 'DHA', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 109, '07aba47e9677:109', now(), 'DANIYAL'),
  ('Abbas Autos', 'Abbas Autos', 'ABBAS AUTOS', 'AIRPORT', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 110, '07aba47e9677:110', now(), 'DANIYAL'),
  ('Abid Autos', 'Abid Autos', 'ABID AUTOS', 'MDL CLNY', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 111, '07aba47e9677:111', now(), 'DANIYAL'),
  ('AG Gun', 'AG Gun', 'AG GUN', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 112, '07aba47e9677:112', now(), 'DANIYAL'),
  ('Agha Hardware', 'Agha Hardware', 'AGHA HARDWARE', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 113, '07aba47e9677:113', now(), 'DANIYAL'),
  ('Al Faisal Autos', 'Al Faisal Autos', 'AL FAISAL AUTOS', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 114, '07aba47e9677:114', now(), 'DANIYAL'),
  ('Al Karim Paint', 'Al Karim Paint', 'AL KARIM PAINT', 'GIZRI', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 115, '07aba47e9677:115', now(), 'DANIYAL'),
  ('Al Madina Autos', 'Al Madina Autos', 'AL MADINA AUTOS', 'AIRPORT', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 116, '07aba47e9677:116', now(), 'DANIYAL'),
  ('Al Madina Hardware', 'Al Madina Hardware', 'AL MADINA HARDWARE', 'MANZOOR CLNY', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 117, '07aba47e9677:117', now(), 'DANIYAL'),
  ('Al Tariq Paint', 'Al Tariq Paint', 'AL TARIQ PAINT', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 118, '07aba47e9677:118', now(), 'DANIYAL'),
  ('Al-Asim Paint', 'Al-Asim Paint', 'ALASIM PAINT', 'DHA', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 119, '07aba47e9677:119', now(), 'DANIYAL'),
  ('Amin Paint', 'Amin Paint', 'AMIN PAINT', 'DHA', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", true, 'Possible duplicate of: JAMI PAINT (row 157)', '07aba47e9677', 120, '07aba47e9677:120', now(), 'DANIYAL'),
  ('Anwer Autos', 'Anwer Autos', 'ANWER AUTOS', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 121, '07aba47e9677:121', now(), 'DANIYAL'),
  ('AQ Son''s BDY PRTS', 'AQ Son''s BDY PRTS', 'AQ SONS BDY PRTS', 'AIRPORT', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 122, '07aba47e9677:122', now(), 'DANIYAL'),
  ('AQ Sons''s Autos', 'AQ Sons''s Autos', 'AQ SONSS AUTOS', 'AIRPORT', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 123, '07aba47e9677:123', now(), 'DANIYAL'),
  ('Aqib Autos', 'Aqib Autos', 'AQIB AUTOS', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 124, '07aba47e9677:124', now(), 'DANIYAL'),
  ('Ars Electronic', 'Ars Electronic', 'ARS ELECTRONIC', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 125, '07aba47e9677:125', now(), 'DANIYAL'),
  ('Arshad And Sons', 'Arshad And Sons', 'ARSHAD AND SONS', 'KHRDR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 126, '07aba47e9677:126', now(), 'DANIYAL'),
  ('Aslam Autos', 'Aslam Autos', 'ASLAM AUTOS', 'CLIFTON', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: ASLAM AUTOS (row 128)', '07aba47e9677', 127, '07aba47e9677:127', now(), 'DANIYAL'),
  ('Aslam Autos', 'Aslam Autos', 'ASLAM AUTOS', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: ASLAM AUTOS (row 127)', '07aba47e9677', 128, '07aba47e9677:128', now(), 'DANIYAL'),
  ('Baba Fareed Autos', 'Baba Fareed Autos', 'BABA FAREED AUTOS', 'GIZRI', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 129, '07aba47e9677:129', now(), 'DANIYAL'),
  ('Baloch Autos', 'Baloch Autos', 'BALOCH AUTOS', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 130, '07aba47e9677:130', now(), 'DANIYAL'),
  ('Bandook Wala', 'Bandook Wala', 'BANDOOK WALA', 'DHA 5', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 131, '07aba47e9677:131', now(), 'DANIYAL'),
  ('BM Autos', 'BM Autos', 'BM AUTOS', 'AIRPORT', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 132, '07aba47e9677:132', now(), 'DANIYAL'),
  ('BS Autos', 'BS Autos', 'BS AUTOS', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 133, '07aba47e9677:133', now(), 'DANIYAL'),
  ('Bukhari Autos Yousaf', 'Bukhari Autos Yousaf', 'BUKHARI AUTOS YOUSAF', 'DHA', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 134, '07aba47e9677:134', now(), 'DANIYAL'),
  ('Bukhari Hardware', 'Bukhari Hardware', 'BUKHARI HARDWARE', 'NURSERY', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 135, '07aba47e9677:135', now(), 'DANIYAL'),
  ('Bukhari Oil', 'Bukhari Oil', 'BUKHARI OIL', 'DHA 5', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 136, '07aba47e9677:136', now(), 'DANIYAL'),
  ('BY The Way Byco', 'BY The Way Byco', 'BY THE WAY BYCO', 'PHASE 8', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 137, '07aba47e9677:137', now(), 'DANIYAL'),
  ('Car Care Zone', 'Car Care Zone', 'CAR CARE ZONE', 'MDL CLNY', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 138, '07aba47e9677:138', now(), 'DANIYAL'),
  ('Color Bank', 'Color Bank', 'COLOR BANK', 'GIZRI', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 139, '07aba47e9677:139', now(), 'DANIYAL'),
  ('Color Point', 'Color Point', 'COLOR POINT', 'NURSERY', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 140, '07aba47e9677:140', now(), 'DANIYAL'),
  ('Cornich Paint', 'Cornich Paint', 'CORNICH PAINT', 'DHA 5', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 141, '07aba47e9677:141', now(), 'DANIYAL'),
  ('Credible Logistics Network', 'Credible Logistics Network', 'CREDIBLE LOGISTICS NETWORK', 'MARIPUR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 142, '07aba47e9677:142', now(), 'DANIYAL'),
  ('Daniyal Sampling Account', 'Daniyal Sampling Account', 'DANIYAL SAMPLING ACCOUNT', '---', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 143, '07aba47e9677:143', now(), 'DANIYAL'),
  ('Daniyal Supply Cash Sales', 'Daniyal Supply Cash Sales', 'DANIYAL SUPPLY CASH SALES', '---', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 144, '07aba47e9677:144', now(), 'DANIYAL'),
  ('DMS Motors', 'DMS Motors', 'DMS MOTORS', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 145, '07aba47e9677:145', now(), 'DANIYAL'),
  ('DR Color', 'DR Color', 'DR COLOR', 'GIZRI', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 146, '07aba47e9677:146', now(), 'DANIYAL'),
  ('Ehsaan Autos', 'Ehsaan Autos', 'EHSAAN AUTOS', 'AIRPORT', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 147, '07aba47e9677:147', now(), 'DANIYAL'),
  ('Friend Autos', 'Friend Autos', 'FRIEND AUTOS', 'MODEL COLONY', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 148, '07aba47e9677:148', now(), 'DANIYAL'),
  ('Ghafoor Motors', 'Ghafoor Motors', 'GHAFOOR MOTORS', 'TARIQ RD', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 149, '07aba47e9677:149', now(), 'DANIYAL'),
  ('Ghausia Car AC', 'Ghausia Car AC', 'GHAUSIA CAR AC', 'MODEL COLONY', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 150, '07aba47e9677:150', now(), 'DANIYAL'),
  ('Ghazi Autos', 'Ghazi Autos', 'GHAZI AUTOS', 'DHA 5', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", true, 'Possible duplicate of: GHAZI AUTOS (row 42)', '07aba47e9677', 151, '07aba47e9677:151', now(), 'DANIYAL'),
  ('GO Petroleum Pump', 'GO Petroleum Pump', 'GO PETROLEUM PUMP', 'SHE FAISAL', 'ACTIVE', true, false, false, 'OTHER', 'FUEL_STATION'::"CustomerType", false, null, '07aba47e9677', 152, '07aba47e9677:152', now(), 'DANIYAL'),
  ('H&H Lubricant', 'H&H Lubricant', 'H&H LUBRICANT', 'QAYUMABAD', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 153, '07aba47e9677:153', now(), 'DANIYAL'),
  ('Hussain Traders', 'Hussain Traders', 'HUSSAIN TRADERS', 'DHA 5', 'ACTIVE', true, false, false, 'OTHER', 'DISTRIBUTOR'::"CustomerType", false, null, '07aba47e9677', 154, '07aba47e9677:154', now(), 'DANIYAL'),
  ('Ishaq Car', 'Ishaq Car', 'ISHAQ CAR', 'CLIFTON', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 155, '07aba47e9677:155', now(), 'DANIYAL'),
  ('Ittehad Car Wash', 'Ittehad Car Wash', 'ITTEHAD CAR WASH', 'DHA', 'ACTIVE', true, false, false, 'OTHER', 'CAR_WASH'::"CustomerType", false, null, '07aba47e9677', 156, '07aba47e9677:156', now(), 'DANIYAL'),
  ('Jami Paint', 'Jami Paint', 'JAMI PAINT', 'DHA 4', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", true, 'Possible duplicate of: AMIN PAINT (row 120)', '07aba47e9677', 157, '07aba47e9677:157', now(), 'DANIYAL'),
  ('Japan Hardware', 'Japan Hardware', 'JAPAN HARDWARE', 'MALIR', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 158, '07aba47e9677:158', now(), 'DANIYAL'),
  ('JS Autos', 'JS Autos', 'JS AUTOS', 'DHA 5', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 159, '07aba47e9677:159', now(), 'DANIYAL'),
  ('JS Electronics', 'JS Electronics', 'JS ELECTRONICS', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', null, true, 'Possible duplicate of: KS ELECTRONICS (row 163)', '07aba47e9677', 160, '07aba47e9677:160', now(), 'DANIYAL'),
  ('K.K Zafcom', 'K.K Zafcom', 'KK ZAFCOM', 'DHA', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 161, '07aba47e9677:161', now(), 'DANIYAL'),
  ('Karachi Autos', 'Karachi Autos', 'KARACHI AUTOS', 'AIRPORT', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 162, '07aba47e9677:162', now(), 'DANIYAL'),
  ('KS Electronics', 'KS Electronics', 'KS ELECTRONICS', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', null, true, 'Possible duplicate of: JS ELECTRONICS (row 160)', '07aba47e9677', 163, '07aba47e9677:163', now(), 'DANIYAL'),
  ('MA Hardware', 'MA Hardware', 'MA HARDWARE', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 164, '07aba47e9677:164', now(), 'DANIYAL'),
  ('Madinah Oil', 'Madinah Oil', 'MADINAH OIL', 'MDL CLNY', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 165, '07aba47e9677:165', now(), 'DANIYAL'),
  ('Madinah Paint', 'Madinah Paint', 'MADINAH PAINT', 'MDL CLNY', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 166, '07aba47e9677:166', now(), 'DANIYAL'),
  ('Makkah Oil', 'Makkah Oil', 'MAKKAH OIL', 'KHRDR', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 167, '07aba47e9677:167', now(), 'DANIYAL'),
  ('Mashriq Autos', 'Mashriq Autos', 'MASHRIQ AUTOS', 'MDL CLNY', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 168, '07aba47e9677:168', now(), 'DANIYAL'),
  ('MK Makkah Autos', 'MK Makkah Autos', 'MK MAKKAH AUTOS', 'ZAMZAMA', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 169, '07aba47e9677:169', now(), 'DANIYAL'),
  ('Mohammad Oil', 'Mohammad Oil', 'MOHAMMAD OIL', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 170, '07aba47e9677:170', now(), 'DANIYAL'),
  ('MS Autos', 'MS Autos', 'MS AUTOS', 'DHA 5', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 171, '07aba47e9677:171', now(), 'DANIYAL'),
  ('New Hasmi Motors', 'New Hasmi Motors', 'NEW HASMI MOTORS', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 172, '07aba47e9677:172', now(), 'DANIYAL'),
  ('Nisar Autos', 'Nisar Autos', 'NISAR AUTOS', 'TARIQ RD', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 173, '07aba47e9677:173', now(), 'DANIYAL'),
  ('Nomi Tech', 'Nomi Tech', 'NOMI TECH', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 174, '07aba47e9677:174', now(), 'DANIYAL'),
  ('Patel Electronics', 'Patel Electronics', 'PATEL ELECTRONICS', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 175, '07aba47e9677:175', now(), 'DANIYAL'),
  ('Protech Detailing', 'Protech Detailing', 'PROTECH DETAILING', 'TARIQ RD', 'ACTIVE', true, false, false, 'OTHER', 'DETAILING'::"CustomerType", false, null, '07aba47e9677', 176, '07aba47e9677:176', now(), 'DANIYAL'),
  ('Protexion Car Care', 'Protexion Car Care', 'PROTEXION CAR CARE', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 177, '07aba47e9677:177', now(), 'DANIYAL'),
  ('Pso Pump 110', 'Pso Pump 110', 'PSO PUMP 110', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'FUEL_STATION'::"CustomerType", false, null, '07aba47e9677', 178, '07aba47e9677:178', now(), 'DANIYAL'),
  ('Pso Qurban', 'Pso Qurban', 'PSO QURBAN', 'CLIFTON', 'ACTIVE', true, false, false, 'OTHER', 'FUEL_STATION'::"CustomerType", false, null, '07aba47e9677', 179, '07aba47e9677:179', now(), 'DANIYAL'),
  ('Pso Tuck Shop', 'Pso Tuck Shop', 'PSO TUCK SHOP', 'DHA 7', 'ACTIVE', true, false, false, 'OTHER', 'FUEL_STATION'::"CustomerType", false, null, '07aba47e9677', 180, '07aba47e9677:180', now(), 'DANIYAL'),
  ('Quality Paint', 'Quality Paint', 'QUALITY PAINT', 'AIRPORT', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 181, '07aba47e9677:181', now(), 'DANIYAL'),
  ('Rana Hardware', 'Rana Hardware', 'RANA HARDWARE', 'MANZOOR CLNY', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 182, '07aba47e9677:182', now(), 'DANIYAL'),
  ('S.M Latif', 'S.M Latif', 'SM LATIF', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 183, '07aba47e9677:183', now(), 'DANIYAL'),
  ('Saeed Autos', 'Saeed Autos', 'SAEED AUTOS', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 184, '07aba47e9677:184', now(), 'DANIYAL'),
  ('Safdar Hardware', 'Safdar Hardware', 'SAFDAR HARDWARE', 'SHE-FAISLA', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 185, '07aba47e9677:185', now(), 'DANIYAL'),
  ('Saifullah Store', 'Saifullah Store', 'SAIFULLAH STORE', 'DHA 4', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 186, '07aba47e9677:186', now(), 'DANIYAL'),
  ('SB Hardware', 'SB Hardware', 'SB HARDWARE', 'NURSERY', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 187, '07aba47e9677:187', now(), 'DANIYAL'),
  ('Shagufta Paint', 'Shagufta Paint', 'SHAGUFTA PAINT', 'NURSERY', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 188, '07aba47e9677:188', now(), 'DANIYAL'),
  ('Shell Select', 'Shell Select', 'SHELL SELECT', 'KORNAGI', 'ACTIVE', true, false, false, 'OTHER', 'FUEL_STATION'::"CustomerType", true, 'Possible duplicate of: SHELL SELECT (row 190); SHELL SELECT (row 191)', '07aba47e9677', 189, '07aba47e9677:189', now(), 'DANIYAL'),
  ('Shell Select', 'Shell Select', 'SHELL SELECT', 'PHASE 4', 'ACTIVE', true, false, false, 'OTHER', 'FUEL_STATION'::"CustomerType", true, 'Possible duplicate of: SHELL SELECT (row 189); SHELL SELECT (row 191)', '07aba47e9677', 190, '07aba47e9677:190', now(), 'DANIYAL'),
  ('Shell Select', 'Shell Select', 'SHELL SELECT', 'CREEK VISTA', 'ACTIVE', true, false, false, 'OTHER', 'FUEL_STATION'::"CustomerType", true, 'Possible duplicate of: SHELL SELECT (row 189); SHELL SELECT (row 190)', '07aba47e9677', 191, '07aba47e9677:191', now(), 'DANIYAL'),
  ('Shera Autos Rohan', 'Shera Autos Rohan', 'SHERA AUTOS ROHAN', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 192, '07aba47e9677:192', now(), 'DANIYAL'),
  ('Sheraz Auto', 'Sheraz Auto', 'SHERAZ AUTO', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 193, '07aba47e9677:193', now(), 'DANIYAL'),
  ('Sindh Paint', 'Sindh Paint', 'SINDH PAINT', 'GIZRI', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 194, '07aba47e9677:194', now(), 'DANIYAL'),
  ('SK Oil', 'SK Oil', 'SK OIL', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 195, '07aba47e9677:195', now(), 'DANIYAL'),
  ('Star Acc', 'Star Acc', 'STAR ACC', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 196, '07aba47e9677:196', now(), 'DANIYAL'),
  ('Subhan Oil', 'Subhan Oil', 'SUBHAN OIL', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', 'OIL_CHANGE'::"CustomerType", false, null, '07aba47e9677', 197, '07aba47e9677:197', now(), 'DANIYAL'),
  ('Subhan Store', 'Subhan Store', 'SUBHAN STORE', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 198, '07aba47e9677:198', now(), 'DANIYAL'),
  ('Super Galaxy Tools', 'Super Galaxy Tools', 'SUPER GALAXY TOOLS', 'SADDAR', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 199, '07aba47e9677:199', now(), 'DANIYAL'),
  ('Super Key Maker', 'Super Key Maker', 'SUPER KEY MAKER', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 200, '07aba47e9677:200', now(), 'DANIYAL'),
  ('Syed Autos', 'Syed Autos', 'SYED AUTOS', 'DHA 5', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 201, '07aba47e9677:201', now(), 'DANIYAL'),
  ('Tanoli Autos', 'Tanoli Autos', 'TANOLI AUTOS', 'MALIR', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 202, '07aba47e9677:202', now(), 'DANIYAL'),
  ('Tawaqal Paint', 'Tawaqal Paint', 'TAWAQAL PAINT', 'GIZRI', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 203, '07aba47e9677:203', now(), 'DANIYAL'),
  ('Touheed Hardware', 'Touheed Hardware', 'TOUHEED HARDWARE', 'DHA', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 204, '07aba47e9677:204', now(), 'DANIYAL'),
  ('Toyota TSM', 'Toyota TSM', 'TOYOTA TSM', 'DHA 1', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 205, '07aba47e9677:205', now(), 'DANIYAL'),
  ('Waleed Store', 'Waleed Store', 'WALEED STORE', 'DHA 4', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 206, '07aba47e9677:206', now(), 'DANIYAL'),
  ('Waseem Paint', 'Waseem Paint', 'WASEEM PAINT', 'DHA 5', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 207, '07aba47e9677:207', now(), 'DANIYAL'),
  ('Wash Car', 'Wash Car', 'WASH CAR', 'SHE FAISAL', 'ACTIVE', true, false, false, 'OTHER', 'CAR_WASH'::"CustomerType", false, null, '07aba47e9677', 208, '07aba47e9677:208', now(), 'DANIYAL'),
  ('X3M', 'X3M', 'X3M', 'DHA 2', 'ACTIVE', true, false, false, 'OTHER', null, false, null, '07aba47e9677', 209, '07aba47e9677:209', now(), 'DANIYAL'),
  ('Zaidi Traders', 'Zaidi Traders', 'ZAIDI TRADERS', 'DHA 5', 'ACTIVE', true, false, false, 'OTHER', 'DISTRIBUTOR'::"CustomerType", false, null, '07aba47e9677', 210, '07aba47e9677:210', now(), 'DANIYAL'),
  ('ZM Motors', 'ZM Motors', 'ZM MOTORS', 'TARIQ RD', 'ACTIVE', true, false, false, 'OTHER', 'AUTO_PARTS'::"CustomerType", false, null, '07aba47e9677', 211, '07aba47e9677:211', now(), 'DANIYAL'),
  ('Zubair Hardware', 'Zubair Hardware', 'ZUBAIR HARDWARE', 'GIZRI', 'ACTIVE', true, false, false, 'OTHER', 'PAINT_HARDWARE'::"CustomerType", false, null, '07aba47e9677', 212, '07aba47e9677:212', now(), 'DANIYAL')
on conflict (import_key) do nothing;

-- Agents created before this migration: assign their customers now.
update public.customers c
   set assigned_agent_id = sa.id, updated_at = now()
  from public.sales_agents sa
 where c.assigned_agent_id is null
   and c.import_agent_alias = public.canonical_agent_alias(sa.agent_code);
